abstract: Decode all templates by Unicode::Japanese
author: Hironori Yoshida  C<< <yoshida@cpan.org> >>
distribution_type: module
generated_by: Module::Install version 0.630
license: perl
name: Template-Provider-Unicode-Japanese
no_index: 
  directory: 
    - inc
    - t
requires: 
  Template: 0
  Unicode::Japanese: 0
  version: 0
version: 0.01
